apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
  namespace: poc-lb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
        - name: my-node-app
          image: my-node-app
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
