apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-node-app
  namespace: poc-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-node-app
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20
